name: configuration_service
description: Enables applications to read JSON configuration files
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  recase: ^4.1.0
# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
