name: configuration_service
description: Enables applications to read JSON configuration files
version: 1.0.4
homepage: https://www.evoleen.com
repository: https://github.com/evoleen/configuration_service
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  recase: ^4.1.0
# path: ^1.8.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
